// ── Kubernetes ─────────────────────────────────────────────

export const k8s = [
  {
    id: 'k8s-not-running',
    title: 'Find all pods NOT in Running state',
    description: 'Quickly surfaces CrashLoopBackOff, Pending, Evicted, and other unhealthy pods across all namespaces',
    command: `kubectl get pods -A --field-selector=status.phase!=Running --no-headers`,
    platform: 'bash',
    tags: ['k8s', 'pods', 'debug', 'status'],
    category: 'k8s',
  },
  {
    id: 'k8s-events-recent',
    title: 'Recent cluster events sorted by time',
    description: 'Shows the last 30 cluster events — fastest way to spot scheduling failures, OOM kills, and pull errors',
    command: `kubectl get events -A --sort-by='.lastTimestamp' | tail -30`,
    platform: 'bash',
    tags: ['k8s', 'events', 'debug', 'cluster'],
    category: 'k8s',
  },
  {
    id: 'k8s-crash-logs',
    title: 'Get logs from a crashed/restarting pod',
    description: 'Fetches logs from the previous container instance — essential for CrashLoopBackOff debugging',
    command: `kubectl logs POD_NAME --previous -n NAMESPACE`,
    platform: 'bash',
    tags: ['k8s', 'logs', 'crash', 'debug'],
    category: 'k8s',
  },
  {
    id: 'k8s-resource-usage',
    title: 'Node resource usage (CPU & memory)',
    description: 'Shows actual vs allocatable resources per node — find overcommitted nodes instantly',
    command: `kubectl top nodes --sort-by=cpu`,
    platform: 'bash',
    tags: ['k8s', 'nodes', 'cpu', 'memory', 'monitoring'],
    category: 'k8s',
  },
  {
    id: 'k8s-pod-resources',
    title: 'Top resource-consuming pods',
    description: 'Ranks pods by CPU usage across all namespaces — find the noisy neighbors',
    command: `kubectl top pods -A --sort-by=cpu | head -20`,
    platform: 'bash',
    tags: ['k8s', 'pods', 'cpu', 'monitoring', 'resources'],
    category: 'k8s',
  },
  {
    id: 'k8s-debug-pod',
    title: 'Spin up a temporary debug pod',
    description: 'Launches an ephemeral pod with common tools in a specific namespace for network or DNS testing',
    command: `kubectl run debug-pod --rm -it --restart=Never \\
  --image=nicolaka/netshoot -n NAMESPACE -- bash`,
    platform: 'bash',
    tags: ['k8s', 'debug', 'networking', 'ephemeral'],
    category: 'k8s',
  },
  {
    id: 'k8s-secret-decode',
    title: 'Decode a Kubernetes secret',
    description: 'Extracts and base64-decodes a secret value — no more piping through base64 manually',
    command: `kubectl get secret SECRET_NAME -n NAMESPACE -o jsonpath='{.data.password}' | base64 -d`,
    platform: 'bash',
    tags: ['k8s', 'secrets', 'decode', 'extract'],
    category: 'k8s',
  },
  {
    id: 'k8s-restart-deployment',
    title: 'Rolling restart a deployment',
    description: 'Triggers a zero-downtime rolling restart without changing the spec',
    command: `kubectl rollout restart deployment/DEPLOYMENT_NAME -n NAMESPACE`,
    platform: 'bash',
    tags: ['k8s', 'deployment', 'restart', 'rollout'],
    category: 'k8s',
  },
  {
    id: 'k8s-all-images',
    title: 'List all container images in the cluster',
    description: 'Extracts every unique image:tag running across all pods — useful for audits and CVE checks',
    command: `kubectl get pods -A -o jsonpath='{range .items[*]}{range .spec.containers[*]}{.image}{"\\n"}{end}{end}' | sort -u`,
    platform: 'bash',
    tags: ['k8s', 'images', 'audit', 'security'],
    category: 'k8s',
  },
  {
    id: 'k8s-port-forward',
    title: 'Port-forward to a pod or service',
    description: 'Exposes a pod or service port to your local machine — access remote services at localhost',
    command: `kubectl port-forward svc/SERVICE_NAME 8080:80 -n NAMESPACE`,
    platform: 'bash',
    tags: ['k8s', 'port-forward', 'networking', 'debug', 'service'],
    category: 'k8s',
  },
  {
    id: 'k8s-copy-files',
    title: 'Copy files to/from a pod',
    description: 'Transfer files between your local machine and a running pod',
    command: `# Copy local file to pod
kubectl cp local-file.txt NAMESPACE/POD_NAME:/tmp/file.txt

# Copy from pod to local
kubectl cp NAMESPACE/POD_NAME:/app/logs/error.log ./error.log`,
    platform: 'bash',
    tags: ['k8s', 'files', 'copy', 'transfer', 'debug'],
    category: 'k8s',
  },
  {
    id: 'k8s-pods-by-label',
    title: 'Get pods by label selector',
    description: 'Filters pods using label queries — essential for microservice debugging',
    command: `kubectl get pods -n NAMESPACE -l app=my-service,env=production -o wide`,
    platform: 'bash',
    tags: ['k8s', 'pods', 'labels', 'selector', 'filter'],
    category: 'k8s',
  },
  {
    id: 'k8s-exec-into-pod',
    title: 'Shell into a running pod',
    description: 'Opens an interactive shell inside a pod — falls back to sh if bash is unavailable',
    command: `kubectl exec -it POD_NAME -n NAMESPACE -- bash || kubectl exec -it POD_NAME -n NAMESPACE -- sh`,
    platform: 'bash',
    tags: ['k8s', 'exec', 'shell', 'debug'],
    category: 'k8s',
  },
];
